name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Use pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: {% raw %}pip-${{ hashFiles('**/requirements*.txt') }}{% endraw %}
          restore-keys: |
            pip-
      - name: Install development tools
        run: pip install -r requirements.dev.txt
      - name: Check formatting
        run: |
          black .
          isort .
      - name: Check docstrings
        run: pydocstyle src/{{ cookiecutter.package_name }}
      - name: Install package
        run: |
          pip install wheel hail
          pip install .
      - name: Run Pylint
        run: |
          pylint src/{{ cookiecutter.package_name }}
          pylint tests
      - name: Run tests
        run: pytest
  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Use pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: {% raw %}pip-${{ hashFiles('**/requirements*.txt') }}{% endraw %}
          restore-keys: |
            pip-
      - name: Install nox
        run: pip install nox
      - name: Build docs
        run: nox -s build_docs
      - name: Publish to GitHub Pages
        if: github.event_name == 'push'
        run: |
          # Create empty gh-pages branch
          git checkout --orphan gh-pages

          # Remove files other than docs
          git rm -rf .
          rm -rf .nox
          find . -name __pycache__ | xargs rm -r

          # Move docs to root
          mv docs/html/* ./
          rm -r docs

          # Prevent GitHub from assuming that this is a Jekyll site
          touch .nojekyll

          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git add .
          git commit --allow-empty -m "Update docs"

          git push --force origin gh-pages

          # Restore the original working tree by checking out the
          # commit that triggered the workflow.
          # This restores requirements.txt so that @actions/cache
          # can use it for determining the cache key.
          git checkout ${GITHUB_SHA}
