---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: "21.9b0" # This should be kept in sync with the version in requirements.dev.in
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: "5.9.3" # This should be kept in sync with the version in requirements.dev.in
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/pydocstyle
    rev: "6.1.1" # This should be kept in sync with the version in requirements.dev.in
    hooks:
      - id: pydocstyle
        additional_dependencies: ["toml"]
        files: src/{{ cookiecutter.package_name }}
